autostart = [
  "waybar",
  "mako",
  "lxqt-policykit-agent",
  "swayidle -w timeout 300 'swaylock -f -c 111318'"
]

window_placement = "auto"

[background]
type = "shader"
path = "~/.config/driftwm/shaders/glslsandbox-108166.glsl"
animate_fps = 60

[session]
restore_windows = false
restore_camera = true

[input.keyboard]
layout = "us,ru"
options = "grp:win_space_toggle"
layout_independent = true

[keybindings]
"mod+l" = "spawn swaylock -f -c 111318"
"Print" = "spawn grim -g \"$(slurp)\" - | wl-copy"
