autostart = [
  "waybar",
  "mako",
  "lxqt-policykit-agent",
  "swayidle -w timeout 1800 'swaylock -f -c 00000000'"
]

window_placement = "auto"

[panel]
autohide = true
namespace = "waybar"
edge_size = 3
hide_delay_ms = 300

[background]
type = "shader"
path = "~/.config/driftwm/shaders/glslsandbox-108166.glsl"
animate_fps = 60
animation_speed = 1.0
lock_animation_speed = 0.5
speed_transition_duration_ms = 1000
speed_transition_easing = "ease-in-out"
show_on_lock_screen = true

[session]
restore_windows = false
restore_camera = true

[input.keyboard]
layout = "us,ru"
options = "grp:win_space_toggle"
layout_independent = true

[keybindings]
"mod+l" = "spawn swaylock -f -c 00000000"
"Print" = "spawn grim -g \"$(slurp)\" - | wl-copy"
